language: python
os:
    - linux
    - osx
python:
    - "3.5"
    - "3.6"
    - "3.7"
cache: pip
install:
    - pip install cffi pytest flake8 networkx
    - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then pip install black; fi
    - pip install .
script:
    - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then black mip --line-length=79 --check; fi
    - flake8 mip --select=F401 --exclude=__init__.py # Look for unused imports
    - pytest test --verbose --color=yes --doctest-modules
    - pytest mip --verbose --color=yes --doctest-modules --ignore="mip/gurobi.py"
jobs:
  include:
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
  allow_failures:
    - os: osx
