environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x" # currently 3.6.5
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x" # currently 3.6.5
      PYTHON_ARCH: "64"

build: off

install:
  - "%PYTHON%\\python.exe -m pip install cffi pytest networkx"
  - "%PYTHON%\\python.exe -m pip install ."
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

test_script:
- cd test ; pytest . --verbose --color=yes --doctest-modules ; cd ..
- cd mip ; pytest . --verbose --color=yes --doctest-modules --ignore="gurobi.py" ; cd ..
- # Ensure that the examples used in the docs run (TODO: Generalize this)
- python examples/knapsack.py
- python examples/tsp-compact.py
- python examples/queens.py
- python examples/bmcp.py
- python examples/rcpsp.py
- python examples/jssp.py
- python examples/cutting_planes.py

